name: Deploy Go Course

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      rebuild_backend:
        description: 'Пересобрать и обновить Go бинарник?'
        required: true
        type: boolean
        default: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.rebuild_backend == 'true' }}
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Build Go Binary
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.rebuild_backend == 'true' }}
        run: |
          GOOS=linux GOARCH=amd64 go build -ldflags "-X main.AppSalt=${{ secrets.APP_SALT }}" -o main main.go

      # Остановка сервиса перед обновлением (чтобы файл не был занят)
      - name: Stop Service
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.rebuild_backend == 'true' }}
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: systemctl stop go-course || true

      # Деплой файлов
      - name: Deploy to Server via SSH
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: ${{ (github.event_name == 'workflow_dispatch' && github.event.inputs.rebuild_backend == 'true') && 'main,frontend/' || 'frontend/' }}
          target: "/root/go-course/"
          overwrite: true

      # Запуск сервиса после обновления
      - name: Start Service
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.rebuild_backend == 'true' }}
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            systemctl start go-course
            systemctl status go-course | grep -E "Active:"
